apiVersion: v1
kind: Namespace
metadata:
  name: test-application

---

apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedNamespace
metadata:
  name: test-application
  namespace: test-application
spec:
  placement:
    clusterNames:
    - europe
    - asia
    - north-america
    - aws-eks
